agol_indexer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^admin/', admin.site.urls, name='admin'),
	url(r'^$', views.index_home, name='index'),
	url(r'^viewer/', include('viewer.urls'), name='viewer'),
	url(r'^join/', include('joins.urls'), name='joins'),
]

joins/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.joins_group, name="joins"),
    url(r'^groups/$', views.joins_group, name="joins_groups"),
    url(r'^mxds/$', views.joins_MXD, name="joins_mxds"),
    url(r'^groups/(?P<group_id>(\d+))$', views.joins_getGroup, name="joins_groups"),
    url(r'^mxds/(?P<mxd_id>(\d+))$', views.joins_getMXD, name="joins_mxds"),

    # CREATE
    url(r'^groups/create$', views.group_create, name="joins_groups_create"),
    url(r'^mxds/create$', views.mxd_create, name="joins_mxds_create"),

    # REMOVE
    url(r'^groups/(?P<id_a>(\d+))/agol/(?P<id_b>(\d+))/delete$', views.group_agol_delete, name="joins_groups_agol_delete"),
    url(r'^groups/(?P<id_a>(\d+))/webmap/(?P<id_b>(\d+))/delete$', views.group_webmap_delete, name="joins_groups_webmap_delete"),
    url(r'^groups/(?P<id_a>(\d+))/webmapapp/(?P<id_b>(\d+))/delete$', views.group_webmap_app_delete, name="joins_groups_webmapapp_delete"),

    url(r'^mxds/(?P<id_a>(\d+))/layersource/(?P<id_b>(\d+))/delete$', views.mxd_layersource_delete, name="joins_mxds_layersource_delete"),

    # ADD
    url(r'^groups/(?P<id_a>(\d+))/agol/(?P<id_b>(\d+))/add$', views.group_agol_add, name="joins_groups_agol_add"),
    url(r'^groups/(?P<id_a>(\d+))/webmap/(?P<id_b>(\d+))/add$', views.group_webmap_add, name="joins_groups_webmap_add"),
    url(r'^groups/(?P<id_a>(\d+))/webmapapp/(?P<id_b>(\d+))/add$', views.group_webmap_app_add, name="joins_groups_webmapapp_add"),

    url(r'^mxds/(?P<id_a>(\d+))/layersource/(?P<id_b>(\d+))/add$', views.mxd_layersource_add, name="joins_mxds_layersource_add"),
]

groups/models.py
from __future__ import unicode_literals
from django.db import models
from webmap.models import Webmap, Webmap_App
from agol.models import AGOL_Item


class GroupManager(models.Manager):
    def create_group(self, name, description):
        group = self.create(name=name, description=description)
        return group


class Group(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=255, blank=True)
    webmap = models.ManyToManyField(Webmap)
    webmap_app = models.ManyToManyField(Webmap_App)
    agol = models.ManyToManyField(AGOL_Item)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    objects = GroupManager()

    dependencies = ['agol', 'webmap', 'webmap_app']
    reverse_dependencies = []

    class Meta:
        verbose_name = 'AGOL Group'
        ordering = ['name']

    def __str__(self):
        return self.name

mxd/models.py
from __future__ import unicode_literals
from django.db import models
from layer_source.models import Layer_Source


class MxdManager(models.Manager):
    def create_mxd(self, name, created_on, client_id, created_by_id, path, description):
        mxd = self.create(name=name, created_on=created_on, client_id=client_id, created_by_id=created_by_id, path=path, description=description)
        return mxd


class MXD_Client(models.Model):
    client = models.CharField(max_length=120)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'MXD Client'
        ordering = ['client']

    def __str__(self):
        return self.client


class MXD_Creator(models.Model):
    creator = models.CharField(max_length=120)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'MXD Creator'
        ordering = ['creator']

    def __str__(self):
        return self.creator


class MXD(models.Model):
    name = models.CharField(max_length=60)
    path = models.CharField(max_length=500)
    description = models.TextField(max_length=255, blank=True)
    client = models.ForeignKey(MXD_Client)
    created_by = models.ForeignKey(MXD_Creator)
    created_on = models.DateTimeField()
    layer_source = models.ManyToManyField(Layer_Source)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    objects = MxdManager()

    dependencies = ['layer_source']
    reverse_dependencies = ['agol_item_set', 'web_service_set']

    class Meta:
        verbose_name = 'MXD'
        ordering = ['name']

    def __str__(self):
        return self.name

templates/partials/card_agol.html
<div class="ui fluid card">
    <div class="content">
        <div class="header">
            <a href="/viewer/agols/?id={{a.id}}">{{ a.name }}</a>
            <a href="{% url 'admin:agol_agol_item_change' a.id  %}" data-tooltip="Edit AGOL Item" data-position="bottom center" class="edit-card" target="_blank">
                <i class="write icon"></i>
            </a>
            <a href="{% url 'dependencies_agol' %}?id={{a.id}}" data-tooltip="View Dependency Report" data-position="bottom center" class="edit-card">
                <i class="browser icon"></i>
            </a>
        </div>
        <div class="meta">
            <span>Created on: </span>
            {{ a.created_date }}
        </div>
        <div class="meta">
            <span> | Updated on: </span>
            {{ a.updated_date }}
        </div>
        <div class="card-accordion ui fluid accordion">
            <div class="title expand-min-item">
                <span class="accord-exp-min">expand</span>
                <i class="icon caret down"></i>
            </div>
            <div class="description content">
                <p>
                    <span>Type: </span>
                    {{ a.type }}
                </p>
                <p>
                    <span> Web Service: </span>
                    <a href="{% url 'viewer_web_service' %}?id={{a.url.id}}" data-tooltip="Link to Web Service view" data-position="right center">{{ a.url }}</a>
                </p>
                <p>
                    <span>External MXD: </span>
                    <a href="{% url 'viewer_mxd' %}?id={{a.mxd_id}}" data-tooltip="Link to MXD view" data-position="right center">{{ a.mxd }}</a>
                </p>
                <p>
                    <span>External Layer URL: </span>
                    <a href="{{a.external_layer_url}}" target="_blank" data-tooltip="External link" data-position="right center">{{ a.external_layer_url }}</a>
                </p>
                <p>
                    <span>Owner: </span>
                    <a href="{% url 'viewer_user' %}?id={{a.owner_id}}" data-tooltip="Link to User view" data-position="right center">{{ a.owner }}</a>
                </p>
                <p>
                    <span>Comments: </span>
                    {{ a.comments }}
                </p>
                <ul class="link-list">
                    <span>Group Links:</span>
                    {% for group in a.group_set.all %}
                        <li>
                            <a href="{% url 'viewer_group' %}?id={{group.id}}" data-tooltip="Link to Group view" data-position="right center">{{ group }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <ul class="link-list">
                    <span>Webmap Links:</span>
                    {% for webmap in a.webmaps.all %}
                        <li>
                            <a href="{% url 'viewer_webmap' %}?id={{webmap.id}}" data-tooltip="Link to Webmap view" data-position="right center">{{ webmap }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/card_groups.html
<div class="ui fluid card">
    <div class="content">
        <div class="header">
            <a href="{% url 'viewer_group' %}?id={{g.id}}">{{ g.name }}</a>
            <a href="{% url 'admin:groups_group_change' g.id  %}" data-tooltip="Edit Group" data-position="bottom center" class="edit-card" target="_blank">
                <i class="write icon"></i>
            </a>
            <a href="{% url 'dependencies_group' %}?id={{g.id}}" data-tooltip="View Dependency Report" data-position="bottom center" class="edit-card">
                <i class="browser icon"></i>
            </a>
        </div>
        <div class="meta">
            <span>Created on: </span>
            {{ g.created_date }}
        </div>
        <div class="meta">
            <span> | Updated on: </span>
            {{ g.updated_date }}
        </div>
        <div class="ui fluid accordion card-accordion">
            <div class="title expand-min-item">
                <span class="accord-exp-min">expand</span>
                <i class="icon caret down"></i>
            </div>
            <div class="description content">
                <p>
                    <span>Description: </span>
                    {{ g.description }}
                </p>
                <ul>
                    <span>ArcGIS Online Items: </span>
                    {% for ag in g.agol.all  %}
                        <li>
                            <a href="{% url 'viewer_agol' %}?id={{ag.id}}" data-tooltip="Link to AGOL view" data-position="right center">{{ ag }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <ul class="link-list">
                    <span>Webmaps: </span>
                    {% for web in g.webmap.all  %}
                        <li>
                            <a href="{% url 'viewer_webmap' %}?id={{web.id}}" data-tooltip="Link to Webmap view" data-position="right center">{{ web }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <ul class="link-list">
                    <span>Webmap Apps: </span>
                    {% for wa in g.webmap_app.all  %}
                        <li>
                            <a href="{% url 'viewer_webmap_app' %}?id={{wa.id}}" data-tooltip="Link to Webmap App view" data-position="right center">{{ wa }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/card_layer-source.html
<div class="ui fluid card">
    <div class="content">
        <div class="header">
            <a href="{% url 'viewer_layer_source' %}?id={{ls.id}}">{{ ls.name }}</a>
            <a href="{% url 'admin:layer_source_layer_source_change' ls.id  %}" data-tooltip="Edit Layer Source" data-position="bottom center" class="edit-card" target="_blank">
                <i class="write icon"></i>
            </a>
            <a href="{% url 'dependencies_layer_source' %}?id={{ls.id}}" data-tooltip="View Dependency Report" data-position="bottom center" class="edit-card">
                <i class="browser icon"></i>
            </a>
        </div>
        <div class="meta">
            <span>Created on: </span>
            {{ ls.created_date }}
        </div>
        <div class="meta">
            <span> | Updated on: </span>
            {{ ls.updated_date }}
        </div>
        <div class="ui fluid accordion card-accordion">
            <div class="title expand-min-item">
                <span class="accord-exp-min">expand</span>
                <i class="icon caret down"></i>
            </div>
            <div class="description content">
                <p>
                    <span>Location/Database: </span>
                    {{ ls.location }}
                </p>
                <p>
                    <span>Format: </span>
                    {{ ls.formats }}
                </p>
                <p>
                    <span>Owner: </span>
                    {{ ls.owner }}
                </p>
                <p>
                    <span>Feature Type: </span>
                    {{ ls.feature_type }}
                </p>
                <ul class="link-list">
                    <span>MXD Links:</span>
                    {% for mxd in ls.mxd_set.all %}
                        <li>
                            <a href="{% url 'viewer_mxd' %}?id={{mxd.id}}" data-tooltip="Link to MXD view" data-position="right center">{{ mxd }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/card_mxd.html
<div class="ui fluid card">
    <div class="content">
        <div class="header">
            <a href="{% url 'viewer_mxd' %}?id={{m.id}}">{{ m.name }}</a>
            <a href="{% url 'admin:mxd_mxd_change' m.id  %}" data-tooltip="Edit MXD" data-position="bottom center" class="edit-card" target="_blank">
                <i class="write icon"></i>
            </a>
            <a href="{% url 'dependencies_mxd' %}?id={{m.id}}" data-tooltip="View Dependency Report" data-position="bottom center" class="edit-card">
                <i class="browser icon"></i>
            </a>
        </div>
        <div class="meta">
            <span>Created on: </span>
            {{ m.created_date }}
        </div>
        <div class="meta">
            <span> | Updated on: </span>
            {{ m.updated_date }}
        </div>
        <div class="ui fluid accordion card-accordion">
            <div class="title expand-min-item">
                <span class="accord-exp-min">expand</span>
                <i class="icon caret down"></i>
            </div>
            <div class="description content">
                <p>
                    <span>Path: </span>
                    {{ m.path }}
                </p>
                <p>
                    <span>Description: </span>
                    {{ m.description }}
                </p>
                <p>
                    <span>Client: </span>
                    {{ m.client }}
                </p>
                <p>
                    <span>Created By: </span>
                    {{ m.created_by }}
                </p>
                <p>
                    <span>Created On: </span>
                    {{ m.created_on }}
                </p>
                <ul class="link-list">
                    <span>Layer Sources:</span>
                    {% for ls in m.layer_source.all  %}
                        <li>
                            <a href="{% url 'viewer_layer_source' %}?id={{ls.id}}" data-tooltip="Link to Layer Source view" data-position="right center">{{ ls }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <ul class="link-list">
                    <span>AGOL Links:</span>
                    {% for agol in m.agol_item_set.all %}
                        <li>
                            <a href="{% url 'viewer_agol' %}?id={{agol.id}}" data-tooltip="Link to AGOL view" data-position="right center">{{ agol }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <ul class="link-list">
                    <span>Web Service Links:</span>
                    {% for ws in m.web_service_set.all %}
                        <li>
                            <a href="{% url 'viewer_web_service' %}?id={{ws.id}}" data-tooltip="Link to Web Service view" data-position="right center">{{ ws }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/card_user.html
<div class="ui fluid card">
    <div class="content">
        <div class="header">
            <a href="/viewer/user/?id={{u.id}}">{{ u.name }}</a>
            <a href="{% url 'admin:agol_users_agol_user_change' u.id  %}" data-tooltip="Edit AGOL User" data-position="bottom center" class="edit-card" target="_blank">
                <i class="write icon"></i>
            </a>
        </div>
        <div class="meta">
            <span>Created on: </span>
            {{ u.created_date }}
        </div>
        <div class="meta">
            <span> | Updated on: </span>
            {{ u.updated_date }}
        </div>
        <div class="ui fluid accordion card-accordion">
            <div class="title expand-min-item">
                <span class="accord-exp-min">expand</span>
                <i class="icon caret down"></i>
            </div>
            <div class="description content">
                <p>
                    <span>Role: </span>
                    {{ u.role }}
                </p>
                <p>
                    <span>Comments: </span>
                    {{ u.comments }}
                </p>
                <ul class="link-list">
                    <span>ArcGIS Online Links:</span>
                    {% for agol in u.agol_item_set.all %}
                        <li>
                            <a href="{% url 'viewer_agol' %}?id={{agol.id}}" data-tooltip="Link to AGOL view" data-position="right center">{{ agol }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/card_web-adapter.html
<div class="ui fluid card">
    <div class="content">
        <div class="header">
            <a href="{% url 'viewer_web_adapter' %}?id={{w.id}}">{{ w.machine_name }}</a>
            <a href="{% url 'admin:web_adapter_web_adapter_change' w.id  %}" data-tooltip="Edit Web Adapter" data-position="bottom center" class="edit-card" target="_blank">
                <i class="write icon"></i>
            </a>
        </div>
        <div class="meta">
            <span>Created on: </span>
            {{ w.created_date }}
        </div>
        <div class="meta">
            <span> | Updated on: </span>
            {{ w.updated_date }}
        </div>
        <div class="ui fluid accordion card-accordion">
            <div class="title expand-min-item">
                <span class="accord-exp-min">expand</span>
                <i class="icon caret down"></i>
            </div>
            <div class="description content">
                <p>
                    <span>Enviroment: </span>
                    {{ w.enviroment }}
                </p>
                <p>
                    <span>Alias: </span>
                    <a href="{{w.alias}}" target="_blank" data-tooltip="External link" data-position="right center">{{ w.alias }}</a>
                </p>
                <p>
                    <span>Description: </span>
                    {{ w.description }}
                </p>
                <ul class="link-list">
                    <span>Web Service Links:</span>
                    {% for ws in w.web_service_set.all %}
                        <li>
                            <a href="{% url 'viewer_web_service' %}?id={{ws.id}}" data-tooltip="Link to Web Service view" data-position="right center">{{ ws }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/card_web-service.html
<div class="ui fluid card">
    <div class="content">
        <div class="header">
            <a href="{% url 'viewer_web_service' %}?id={{w.id}}">{{ w.name }}</a>
            <a href="{% url 'admin:web_service_web_service_change' w.id  %}" data-tooltip="Edit Web Service" data-position="bottom center" class="edit-card" target="_blank">
                <i class="write icon"></i>
            </a>
            <a href="{% url 'dependencies_web_service' %}?id={{w.id}}" data-tooltip="View Dependency Report" data-position="bottom center" class="edit-card">
                <i class="browser icon"></i>
            </a>
        </div>
        <div class="meta">
            <span>Created on: </span>
            {{ w.created_date }}
        </div>
        <div class="meta">
            <span> | Updated on: </span>
            {{ w.updated_date }}
        </div>
        <div class="ui fluid accordion card-accordion">
            <div class="title expand-min-item">
                <span class="accord-exp-min">expand</span>
                <i class="icon caret down"></i>
            </div>
            <div class="description content">
                <p>
                    <span>Location: </span>
                    {{ w.location }}
                </p>
                <p>
                    <span>Actual URL: </span>
                    <a href="{{w.actual_url}}" target="_blank" data-tooltip="External link" data-position="right center">{{ w.actual_url }}</a>
                </p>
                <p>
                    <span>Alias URL: </span>
                    <a href="{{w.alias_url}}" target="_blank" data-tooltip="External link" data-position="right center">{{ w.alias_url }}</a>
                </p>
                <p>
                    <span>Level: </span>
                    {{ w.level }}
                </p>
                <p>
                    <span>MXD: </span>
                    <a href="{% url 'viewer_mxd' %}?id={{w.mxd_id}}" data-tooltip="Link to MXD view" data-position="right center">{{ w.mxd }}</a>
                </p>
                <p>
                    <span>Web Adapter: </span>
                    <a href="{% url 'viewer_web_adapter' %}?id={{w.web_adapter_id}}" data-tooltip="Link to Web Adapter view" data-position="right center">{{ w.web_adapter }}</a>
                </p>
                <ul class="link-list">
                    <span>AGOL Links:</span>
                    {% for agol in w.agol_item_set.all %}
                        <li>
                            <a href="{% url 'viewer_agol' %}?id={{agol.id}}" data-tooltip="Link to AGOL view" data-position="right center">{{ agol }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/card_webmap-app.html
<div class="ui fluid card">
    <div class="content">
        <div class="header">
            <a href="{% url 'viewer_webmap_app' %}?id={{w.id}}">{{ w.name }}</a>
            <a href="{% url 'admin:webmap_webmap_app_change' w.id  %}" data-tooltip="Edit Webmap App" data-position="bottom center" class="edit-card" target="_blank">
                <i class="write icon"></i>
            </a>
            <a href="{% url 'dependencies_webmap_app' %}?id={{w.id}}" data-tooltip="View Dependency Report" data-position="bottom center" class="edit-card">
                <i class="browser icon"></i>
            </a>
        </div>
        <div class="meta">
            <span>Created on: </span>
            {{ w.created_date }}
        </div>
        <div class="meta">
            <span> | Updated on: </span>
            {{ w.updated_date }}
        </div>
        <div class="ui fluid accordion card-accordion">
            <div class="title expand-min-item">
                <span class="accord-exp-min">expand</span>
                <i class="icon caret down"></i>
            </div>
            <div class="description content">
                <p>
                    <span>Purpose: </span>
                    {{ w.purpose }}
                </p>
                <p>
                    <span>Url: </span>
                    <a href="{{w.url}}" target="_blank" data-tooltip="External link" data-position="right center">{{ w.url }}</a>
                </p>
                <p>
                    <span>Contact: </span>
                    {{ w.contact }}
                </p>
                <p>
                    <span>Webmap: </span>
                    <a href="{% url 'viewer_webmap' %}?id={{w.webmap_id}}" data-tooltip="Link to Webmap view" data-position="right center">{{ w.webmap }}</a>
                </p>
                <ul class="link-list">
                    <span>Group Links:</span>
                    {% for group in w.group_set.all %}
                        <li>
                            <a href="{% url 'viewer_group' %}?id={{group.id}}" data-tooltip="Link to Group view" data-position="right center">{{ group }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/card_webmap.html
<div class="ui fluid card">
    <div class="content">
        <div class="header">
            <a href="{% url 'viewer_webmap' %}?id={{w.id}}">{{ w.name }}</a>
            <a href="{% url 'admin:webmap_webmap_change' w.id  %}" data-tooltip="Edit Webmap" data-position="bottom center" class="edit-card" target="_blank">
                <i class="write icon"></i>
            </a>
            <a href="{% url 'dependencies_webmap' %}?id={{w.id}}" data-tooltip="View Dependency Report" data-position="bottom center" class="edit-card">
                <i class="browser icon"></i>
            </a>
        </div>
        <div class="meta">
            <span>Created on: </span>
            {{ w.created_date }}
        </div>
        <div class="meta">
            <span> | Updated on: </span>
            {{ w.updated_date }}
        </div>
        <div class="card-accordion ui fluid accordion">
            <div class="title expand-min-item">
                <span class="accord-exp-min">expand</span>
                <i class="icon caret down"></i>
            </div>
            <div class="description content">
                <p>
                    <span>Purpose: </span>
                    {{ w.purpose }}
                </p>
                <p>
                    <span>Contact: </span>
                    {{ w.contact }}
                </p>
                <p>
                    <span>Url: </span>
                    <a href="{{w.url}}" target="_blank" data-tooltip="External link" data-position="right center">{{ w.url }}</a>
                </p>
                <p>
                    <span>Collector: </span>
                    {{ w.collector }}
                </p>
                <p>
                    <span>Collector Offline: </span>
                    {{ w.collector_offline }}
                </p>
                <ul class="link-list">
                    <span>Group Links:</span>
                    {% for g in w.group_set.all %}
                        <li>
                            <a href="{% url 'viewer_group' %}?id={{g.id}}" data-tooltip="Link to Group view" data-position="right center">{{ g }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <ul class="link-list">
                    <span>Webmap App Links:</span>
                    {% for wa in w.webmap_app_set.all %}
                        <li>
                            <a href="{% url 'viewer_webmap_app' %}?id={{wa.id}}" data-tooltip="Link to Webmap App view" data-position="right center">{{ wa }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <ul class="link-list">
                    <span>AGOL Links:</span>
                    {% for agol_item in w.agols.all %}
                        <li>
                            <a href="{% url 'viewer_agol' %}?id={{agol_item.id}}" data-tooltip="Link to AGOL view" data-position="right center">{{ agol_item }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/home_results.html
<div class="ui fluid accordion">
    {% if layer_sources %}
        <div class="ui section divider"></div>
        <div class="title">
            <i class="dropdown icon"></i>
            <span class="ui blue header">{{layer_sources.count}}  Layer Source{{layer_sources.count|pluralize}}</span>
        </div>
        <div class="content">
            <p class="transition hidden">
                {% for ls in layer_sources %}
                    {% include "partials/card_layer-source.html" with ls=ls %}
                {% endfor %}
            </p>
        </div>
    {% endif %}

    {% if mxds %}
        <div class="ui section divider"></div>
        <div class="title">
            <i class="dropdown icon"></i>
            <span class="ui blue header">{{mxds.count}}  MXD{{mxds.count|pluralize}}</span>
        </div>
        <div class="content">
            <p class="transition hidden">
                {% for m in mxds %}
                    {% include "partials/card_mxd.html" with m=m %}
                {% endfor %}
            </p>
        </div>
    {% endif %}

    {% if web_services %}
        <div class="ui section divider"></div>
        <div class="title">
            <i class="dropdown icon"></i>
            <span class="ui blue header">{{web_services.count}}  Web Service{{web_services.count|pluralize}}</span>
        </div>
        <div class="content">
            <p class="transition hidden">
                {% for w in web_services %}
                    {% include "partials/card_web-service.html" with w=w %}
                {% endfor %}
            </p>
        </div>
    {% endif %}

    {% if agols %}
        <div class="ui section divider"></div>
        <div class="title">
            <i class="dropdown icon"></i>
            <span class="ui blue header">{{agols.count}}  ArcGIS Online Item{{agols.count|pluralize}}</span>
        </div>
        <div class="content">
            <p class="transition hidden">
                {% for a in agols %}
                    {% include "partials/card_agol.html" with a=a %}
                {% endfor %}
            </p>
        </div>
    {% endif %}

    {% if webmaps %}
        <div class="ui section divider"></div>
        <div class="title">
            <i class="dropdown icon"></i>
            <span class="ui blue header">{{webmaps.count}}  Webmap{{webmaps.count|pluralize}}</span>
        </div>
        <div class="content">
            <p class="transition hidden">
                {% for w in webmaps %}
                    {% include "partials/card_webmap.html" with w=w %}
                {% endfor %}
            </p>
        </div>
    {% endif %}

    {% if webmap_apps %}
        <div class="ui section divider"></div>
        <div class="title">
            <i class="dropdown icon"></i>
            <span class="ui blue header">{{webmap_apps.count}}  Webmap App{{webmap_apps.count|pluralize}}</span>
        </div>
        <div class="content">
            <p class="transition hidden">
                {% for w in webmap_apps %}
                    {% include "partials/card_webmap-app.html" with w=w %}
                {% endfor %}
            </p>
        </div>
    {% endif %}


    {% if groups %}
        <div class="ui section divider"></div>
        <div class="title">
            <i class="dropdown icon"></i>
            <span class="ui blue header">{{groups.count}}  Group{{groups.count|pluralize}}</span>
        </div>
        <div class="content">
            <p class="transition hidden">
                {% for g in groups %}
                    {% include "partials/card_groups.html" with g=g %}
                {% endfor %}
            </p>
        </div>
    {% endif %}

    {% if web_adapters %}
        <div class="ui section divider"></div>
        <div class="title">
            <i class="dropdown icon"></i>
            <span class="ui blue header">{{web_adapters.count}}  Web Adapter{{web_adapters.count|pluralize}}</span>
        </div>
        <div class="content">
            <p class="transition hidden">
                {% for w in web_adapters %}
                    {% include "partials/card_web-adapter.html" with w=w %}
                {% endfor %}
            </p>
        </div>
    {% endif %}

<div class="ui section divider"></div>
</div>